#! /bin/bash

# get 0 1 for if laughter present in a file or not along with each code
input_dir=$1 #e.g. ../data/to_use_set_discrete
output_dir=$2 #e.g. ../data/to_use_set_01

for file in $input_dir/*
do

	echo $file
	grep -v ^- $file | cut -f1 > temp_code

	# for the set of counselor codes, 1 infront means counselor
	sed -i "s/counselor\.gi/11/g;s/counselor\.fa/12/g;s/counselor\.res/13/g;s/counselor\.rec/13/g;s/counselor\.quo/14/g;s/counselor\.quc/14/g" temp_code
	sed -i "s/counselor[^\ ]*/15/g" temp_code

	# for the set of client codes, 2 infront means client 
	sed -i "s/client\.[a-z]*+[^\t]*/22/g;s/client\.[a-z]*-[^\t]*/23/g" temp_code
	sed -i "s/client[^\t]*/21/g" temp_code

	grep -v ^- $file | cut -f2 > temp_empathy
	sed -i s/global.*/1/g temp_empathy
	sed -i s/-/0/g temp_empathy

	grep -v ^- $file | cut -f3 > temp_laughter
	sed -i s/laugh/1/g temp_laughter
	sed -i s/^$/0/g temp_laughter			

	paste -d',' temp_code temp_empathy temp_laughter > $output_dir/$(basename $file)

done
